version: '3'

services:
  spark-master:
    build: .
    image: my-spark
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    command: >
      bash -c "
      /opt/spark/sbin/start-master.sh --host spark-master --port 7077 --webui-port 8080;
      tail -f /dev/null;
      "
    tty: true
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_MODE=master
    volumes:
      - ./data:/opt/spark/local
      - ./conf:/opt/spark/conf

  spark-worker:
    image: my-spark
    container_name: spark-worker
    hostname: spark-worker
    ports:
      - "8081:8081"
    command: >
      bash -c "
      /opt/spark/sbin/start-worker.sh --webui-port 8081 spark://spark-master:7077;
      tail -f /dev/null;
      "
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_MODE=worker
    depends_on:
      - spark-master
    volumes:
      - ./data:/opt/spark/local