version: "3.7"
services:
  # jupyterlab with pyspark
  pyspark:
    image: jupyter/pyspark-notebook:latest
    environment:
      JUPYTER_ENABLE_LAB: "yes" # Enables JupyterLab
      SPARK_OPTS: "--driver-memory 4g --executor-memory 4g" # Optional: Adjust Spark memory
      JUPYTER_TOKEN: ""
    ports:
      - "8888:8888" # Maps container port 8888 to host port 8888 for Jupyter
      - "4040:4040" # Maps container port 4040 to host port 4040 for Spark UI
      - "4041:4041"
    volumes:
      - ./shared/data:/home/jovyan/work # Mounts a 'data' folder from your host to the container's work directory